- .gitignore
- examples/graph_examples/custom_graph_example.py
- examples/graph_examples/graph_from_text_example.py
- requirements.txt
- scrapegraphai/builders/graph_builder.py
- scrapegraphai/graphs/smart_scraper_graph.py
- scrapegraphai/graphs/speech_summary_graph.py
- scrapegraphai/models/__init__.py
- scrapegraphai/models/gemini.py
- scrapegraphai/nodes/__init__.py
- scrapegraphai/nodes/generate_answer_node_from_rag.py
- scrapegraphai/nodes/generate_answer_node_vanilla.py
- tests/graphs/graph_from_text_test.py
- Support scraping of one page at time with gemini WITHOUT RAG!!!
> DEV gemini support for simple custom graph

- examples/graph_examples/scrape_plain_text.py
- scrapegraphai/graphs/smart_scraper_graph.py
- scrapegraphai/nodes/fetch_node.py
the node from text wads changed, because maybe you can not store the information on the server
> add new type of scraping through text

- examples/local/smart_scraper_local.py
- scrapegraphai/graphs/abstract_graph.py
Here's a PR for https://github.com/VinciGit00/Scrapegraph-ai/issues/51
>  Allow setting Ollama models context length within config #51

- examples/readme.md
Added results from running `benchmark.py` on a ubuntu laptop without docker
> Update readme.md with benchmark on ubuntu system

- scrapegraphai/helpers/models_tokens.py
I added some models among the all-time most popular and the recently trending ones.
> feat: add new hugging_face models

- README.md
> docs: update instructions to use with LocalAI

- scrapegraphai/helpers/models_tokens.py
> chore: update models_tokens.py with new model configurations

- scrapegraphai/helpers/models_tokens.py
I have added support for Gemini Flash and Pro
> Added gemini flash and pro support 

- examples/openai/burr_integration_openai.py
- scrapegraphai/integrations/burr_bridge.py
(also makes the App ID a unique one for debugging, it kept getting confused)
> Updates Burr bridge to use class-based API

- scrapegraphai/nodes/generate_scraper_node.py
> fix: typo in prompt

- scrapegraphai/helpers/models_tokens.py
> add the Ernie context window

- examples/ernie/smart_scraper_schema_ernie.py
- examples/huggingfacehub/smart_scraper_schema_huggingfacehub.py
- examples/mixed_models/smart_scraper_schema_groq_openai.py
- scrapegraphai/graphs/abstract_graph.py
- scrapegraphai/graphs/csv_scraper_multi_graph.py
- scrapegraphai/graphs/deep_scraper_graph.py
- scrapegraphai/graphs/json_scraper_graph.py
- scrapegraphai/graphs/json_scraper_multi_graph.py
- scrapegraphai/graphs/omni_scraper_graph.py
- scrapegraphai/graphs/omni_search_graph.py
- scrapegraphai/graphs/pdf_scraper_graph.py
- scrapegraphai/graphs/pdf_scraper_multi_graph.py
- scrapegraphai/graphs/script_creator_graph.py
- scrapegraphai/graphs/script_creator_multi_graph.py
- scrapegraphai/graphs/search_graph.py
- scrapegraphai/graphs/smart_scraper_graph.py
- scrapegraphai/graphs/smart_scraper_multi_graph.py
- scrapegraphai/graphs/speech_graph.py
- scrapegraphai/graphs/xml_scraper_graph.py
- scrapegraphai/graphs/xml_scraper_multi_graph.py
docs: updated for schema changes
> fix: updated for schema changes

- scrapegraphai/builders/graph_builder.py
- scrapegraphai/helpers/models_tokens.py
This adjustment makes the class consistent with the definition of the arguments.
> 🐛 Rename user_prompt parameter to prompt 

- README.md
- docs/korean.md
In this PR, I have made the following updates:
1. Corrected unnatural translations, such as '코리아노'.
2. Fixed broken parts that may have occurred during automatic translation.
> Fix unnatural Korean translation 

- scrapegraphai/nodes/parse_node.py
> Refactoring of chunking function

- examples/gemini/pdf_scraper_graph_gemini.py
Fix gemini example  for gemini-pro
> chore: update gemini model typo to "gemini-pro"

- scrapegraphai/helpers/models_tokens.py
Fixed the issue of model token selection for the Azure models.
> fix azure-openai models_tokens issue

- examples/anthropic/csv_scraper_graph_multi_haiku.py
- examples/anthropic/csv_scraper_haiku.py
- examples/anthropic/custom_graph_haiku.py
- examples/anthropic/json_scraper_haiku.py
- examples/anthropic/json_scraper_multi_haiku.py
- examples/anthropic/pdf_scraper_graph_haiku.py
- examples/anthropic/pdf_scraper_multi_haiku.py
- examples/anthropic/scrape_plain_text_haiku.py
- examples/anthropic/script_generator_haiku.py
- examples/anthropic/script_multi_generator_haiku.py
- examples/anthropic/search_graph_haiku.py
- examples/anthropic/search_graph_schema_haiku.py
- examples/anthropic/search_link_graph_haiku.py
- examples/anthropic/smart_scraper_haiku.py
- examples/anthropic/smart_scraper_multi_haiku.py
- examples/anthropic/smart_scraper_schema_haiku.py
- examples/anthropic/xml_scraper_graph_multi_haiku.py
- examples/anthropic/xml_scraper_haiku.py
- scrapegraphai/graphs/abstract_graph.py
Reverts ScrapeGraphAI/Scrapegraph-ai#583
> Revert "Anthropic refactoring"

- examples/deepseek/csv_scraper_deepseek.py
- examples/deepseek/csv_scraper_graph_multi_deepseek.py
- examples/deepseek/json_scraper_deepseek.py
- examples/deepseek/json_scraper_multi_deepseek.py
- examples/deepseek/pdf_scraper_graph_deepseek.py
- examples/deepseek/pdf_scraper_multi_deepseek.py
- examples/deepseek/scrape_plain_text_deepseek.py
- examples/deepseek/script_generator_deepseek.py
- examples/deepseek/script_multi_generator_deepseek.py
- examples/deepseek/search_graph_deepseek.py
- examples/deepseek/search_graph_schema_deepseek.py
- examples/deepseek/search_link_graph_deepseek.py
- examples/deepseek/smart_scraper_deepseek.py
- examples/deepseek/smart_scraper_multi_deepseek.py
- examples/deepseek/smart_scraper_schema_deepseek.py
- examples/deepseek/xml_scraper_deepseek.py
- examples/deepseek/xml_scraper_graph_multi_deepseek.py
- examples/oneapi/custom_graph_oneapi.py
- scrapegraphai/graphs/abstract_graph.py
- scrapegraphai/models/deepseek.py
- scrapegraphai/models/oneapi.py
- tests/graphs/abstract_graph_test.py
> Abstract graph fix

- scrapegraphai/graphs/csv_scraper_multi_graph.py
- scrapegraphai/graphs/json_scraper_multi_graph.py
- scrapegraphai/graphs/markdown_scraper_multi_graph.py
- scrapegraphai/graphs/omni_search_graph.py
- scrapegraphai/graphs/pdf_scraper_multi_graph.py
- scrapegraphai/graphs/script_creator_multi_graph.py
- scrapegraphai/graphs/search_graph.py
- scrapegraphai/graphs/smart_scraper_multi_graph.py
- scrapegraphai/graphs/xml_scraper_multi_graph.py
- scrapegraphai/nodes/search_internet_node.py
- scrapegraphai/utils/copy.py
- tests/utils/copy_utils_test.py
I find some search graph cannot alter the search_engine configuration like `search_graph`, which default value is google. but google cannot be used in some region directly. so I exposed the config for some graph as an options.
> feat:expose the search engine params to user

- pyproject.toml
- requirements-dev.lock
- requirements.lock
- requirements.txt
- scrapegraphai/graphs/abstract_graph.py
- tests/graphs/abstract_graph_test.py
> Fix deepseek and ollama instancing

- examples/anthropic/rate_limit_haiku.py
- examples/azure/rate_limit_azure.py
- examples/bedrock/rate_limit_bedrock.py
- examples/deepseek/rate_limit_deepseek.py
- examples/ernie/rate_limit_ernie.py
- examples/fireworks/rate_limit_fireworks.py
- examples/google_genai/rate_limit_gemini.py
- examples/google_vertexai/rate_limit_gemini.py
- examples/groq/rate_limit_groq.py
- examples/mistral/rate_limit_mistral.py
- examples/nemotron/rate_limit_nemotron.py
- examples/oneapi/rate_limit_oneapi.py
- examples/openai/rate_limit_openai.py
- examples/together/rate_limit_together.py
- scrapegraphai/graphs/abstract_graph.py
- tests/graphs/abstract_graph_test.py
Very simple solution that makes use of LangChain's (still primitive) rate limiter
> feat(AbstractGraph): add adjustable rate limit

- scrapegraphai/graphs/abstract_graph.py
- scrapegraphai/nodes/parse_node.py
- scrapegraphai/utils/split_text_into_chunks.py
- scrapegraphai/utils/tokenizer.py
- scrapegraphai/utils/tokenizers/tokenizer_mistral.py
- scrapegraphai/utils/tokenizers/tokenizer_ollama.py
- scrapegraphai/utils/tokenizers/tokenizer_openai.py
Adding the Mistral and Ollama tokenization code to resolve #651
> 651 add tokenization for ollama and mistral

- scrapegraphai/nodes/parse_node.py
Re-added image and link urls parsing capabilities to ParseNode
> 580 - Omni Scraper not working

- scrapegraphai/graphs/search_graph.py
- scrapegraphai/nodes/search_internet_node.py
- scrapegraphai/utils/research_web.py
Integrated Serper API for Google Search to avoid IP blockage from Google.
> feat: Serper API integration for Google search

- .ipynb_checkpoints/Untitled-checkpoint.ipynb
- scrapegraphai/nodes/generate_answer_node.py
> fix: resolved outparser issue

- README.md
Removed duplicated line "**integrations**" in the Readme.md file (line 41-42).
> docs: removed duplicated line
