ScrapeGraphAI/Scrapegraph-ai

examples/local/smart_scraper_local.py
Since you pass `config["llm"]` to langchain ChatOllama(), it's only a matter of adding a new parameter `base_url`.
=> smart_scraper_local.py:  Allow using a remote Ollama #53

scrapegraphai/utils/convert_to_csv.py
No need to raise an error....we can remove the .csv extension.
=> Remove .csv extension from filename in convert_to_csv.py

CONTRIBUTING.md
Fixed text errors in the CONTRIBUTING.md file, where the old repo name was still there.
=> refactor: fixed text errors in CONTRIBUTING.md

.github/workflows/release.yml, .releaserc.yml, CHANGELOG.md, pyproject.toml, scrapegraphai/nodes/__init__.py, scrapegraphai/nodes/search_link_node.py
feaure: search link
bugfix for nodes integration
=> Release v0.3.0

README.md, examples/mixed_models/smart_scraper_mixed.py, pyproject.toml, requirements.txt, scrapegraphai/graphs/search_graph.py, scrapegraphai/graphs/smart_scraper_graph.py, scrapegraphai/graphs/speech_graph.py, scrapegraphai/nodes/fetch_node.py
Now the html pages will be fetched using Playwright.
If after using the browser in headless mode you don't get results, you can set the `headless` flag to False in the graph config. 
```
graph_config = {
"llm": {
"model": "groq/gemma-7b-it",
"api_key": groq_key,
"temperature": 0
},
"embeddings": {
"model": "ollama/nomic-embed-text",
"temperature": 0,
"base_url": "http://localhost:11434",  # set ollama URL arbitrarily
},
"headless": False
}
```
=> feat(fetch): added playwright support

examples/azure/smart_scraper_azure_openai.py, scrapegraphai/graphs/abstract_graph.py, scrapegraphai/helpers/models_tokens.py, scrapegraphai/nodes/rag_node.py
#123 Hi @VinciGit00, I have added support for passing model instances as well, means optionally end user can pass llm / embedding instances as well. So, using this we can support Azure OpenAI as well.
=> enable end users to pass model instances for llm and embeddings model 

examples/groq/smart_scraper_groq_openai.py, scrapegraphai/graphs/abstract_graph.py, scrapegraphai/nodes/rag_node.py
Now instead of using ```self._create_llm()``` method for **both** embedding models and LLMs and delegating the correct instantiation of embedding models to the ```RAGNode``` class, there are two dedicated methods for creating embedding models and the logic is completely inside the ```AbstractGraph``` class:
1. ```self.create_default_embedder()```: This method handles the case where no embedding model is provided in the config. This will try to instantiate the proper embedding model based on the chosen LLM. Previously, this case was handled in the ```self.execute()``` method in the ```RAGNode``` class. I didn't change the code for this part (it's a copy-paste of the old code) so that it works just like it was previously.
2. ```self.create_embedder()```: This method handles the case where …
=> Changed the way embedding model creation is handled in the AbstractGraph class.

examples/huggingfacehub/smart_scraper_huggingfacehub.py, scrapegraphai/graphs/abstract_graph.py, scrapegraphai/helpers/models_tokens.py, scrapegraphai/nodes/rag_node.py
=> Enable end users to pass model instances of HuggingFaceHub

scrapegraphai/models/gemini.py
Replaced the `api_key` param into `google_api_key` in the model definition.
=> fix(llm): fixed gemini api_key

pyproject.toml
pkgutil.ImpImporter has been deprecated in python 3.12 and that makes poetry install crash for those on python 3.12.
Limited the range of accepted python versions for now.
I think the error happens specifically while building yahoo-search-py which I see one of you authored so maybe you can have a look there later.
Fixes https://github.com/VinciGit00/Scrapegraph-ai/issues/189
Sorry for previously closed pr, saw they have to be to pre/beta now.
=> fix: limit python version to < 3.12

requirements.txt, scrapegraphai/graphs/pdf_scraper_graph.py, scrapegraphai/nodes/fetch_node.py
=> Add support for passing pdf path as source

README.md
Reverts VinciGit00/Scrapegraph-ai#205
=> Revert "docs: update instructions to use with LocalAI"

scrapegraphai/graphs/smart_scraper_graph_burr.py
This is a stop gap measure to enable someone to restart
from where things failed. The prior issue was deserializing
LC documents and things that look like them.
This depends on this burr change being published:
Depends on https://github.com/DAGWorks-Inc/burr/pull/175.
=> Fixes LC document deserialization

scrapegraphai/nodes/fetch_node.py, scrapegraphai/utils/__init__.py, scrapegraphai/utils/cleanup_html.py
Commit https://github.com/VinciGit00/Scrapegraph-ai/commit/f8ce3d5916eab926275d59d4d48b0d89ec9cd43f was reverted.
- While changing the target, looks like one of the import was missed. That is now fixed
- For the links within the baseurl, only absolute links were getting retrieved. Now added urlJoin to fetch complete navigable urls: /projects/rotary-pendulum-rl/ -> https://perinim.github.io/projects/rotary-pendulum-rl/
- Moved the logic to fetch urls to the utils
=> Fetch links in the page while parsing html

examples/openai/deep_scraper_openai.py, scrapegraphai/graphs/__init__.py, scrapegraphai/graphs/deep_scraper_graph.py, scrapegraphai/nodes/search_link_node.py, scrapegraphai/utils/cleanup_html.py
This is part 2 of the code changes to support n-level deep web search by following the links in the input page to accomplish a task given in the prompt. [Part 1](https://github.com/VinciGit00/Scrapegraph-ai/pull/217)
Here we modify the SearchLinkNode to filter out the relevant links for the prompts from the input page.
Also added a top-level DeepScrapeGraph which is still a work in progress.
```
(scrape311) ➜  Scrapegraph-ai git:(deepScrape) ✗ python examples/openai/deep_scraper_openai.py
--- Executing Fetch Node ---
--- Executing Parse Node ---
--- Executing RAG Node ---
--- (updated chunks metadata) ---
--- (tokens compressed and vector stored) ---
--- Executing GenerateLinks Node ---
Processing chunks: 100%|████████████████████████████████████████████████████████████████████████████████ …
```
=> feat(n-level deep scrape): Modify SearchLinkNode to find out the relevant links from the webpage

scrapegraphai/graphs/abstract_graph.py, scrapegraphai/helpers/models_tokens.py, scrapegraphai/models/__init__.py, scrapegraphai/models/deepseek.py
=> feat: add support for deepseek-chat

scrapegraphai/graphs/abstract_graph.py, scrapegraphai/models/anthropic.py
This PR adds support for custom AWS credentials passed via graph configs.
**Example:**
```python
import boto3
from scrapegraphai.graphs import SmartScraperGraph
session = boto3.Session(
aws_access_key_id="...",
aws_secret_access_key="...",
aws_session_token="...",
region_name="us-east-1"
)
client = session.client("bedrock-runtime")
config = {
"llm": {
"client": client,
"model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
"temperature": 0.0,
"format": "json"
},
"embeddings": {
"client": client,
"model": "bedrock/cohere.embed-multilingual-v3",
},
}
graph = SmartScraperGraph(
prompt="List me all the articles",
source="https://perinim.github.io/projects",
config=config
)
print(graph.run())
```
=> feat: Custom AWS credentials

scrapegraphai/nodes/search_link_node.py
Just based on the links, it is not possible to tell if the link will contain any relevant information related to prompt. Updates the  prompt to be more optimistic and include such potential links in the search
=> fix: Update the prompt for the search_link_node

scrapegraphai/graphs/base_graph.py, scrapegraphai/nodes/conditional_node.py
The current graph traversal is very sub-optimal and confusing. We were iterating throught all the nodes and then looking for the edges out of this. Also, it was constrained that one node could be connected to another node
For usecases such as n-level deep search, there would be a requirement to add more than child nodes out of the node. For example, pipeline for n-level deep search would look like:
=> fix: Add a new graph traversal that allows more than one edges out of a graph

.gitignore, CHANGELOG.md, pyproject.toml, requirements.txt, scrapegraphai/docloaders/chromium.py, scrapegraphai/helpers/models_tokens.py
Uses a virtually non-intrusive method to hide browser control features. Can bypass most human-authentication algorithms.
=> feat(docloaders): undetected-playwright

scrapegraphai/graphs/abstract_graph.py, scrapegraphai/nodes/robots_node.py
This PR fixes bugs found while testing https://github.com/VinciGit00/Scrapegraph-ai/pull/272
The `ScriptCreatorGraph` class tries to access the `verbose` attribute
https://github.com/VinciGit00/Scrapegraph-ai/blob/f1a25233d650010e1932e0ab80938079a22a296d/scrapegraphai/graphs/script_creator_graph.py#L68
before it is set 
https://github.com/VinciGit00/Scrapegraph-ai/blob/f1a25233d650010e1932e0ab80938079a22a296d/scrapegraphai/graphs/abstract_graph.py#L59
**Example:**
```bash
python examples/bedrock/script_generator_bedrock.py
```
**Before:**
```
AttributeError: 'ScriptCreatorGraph' object has no attribute 'verbose'
```
**After:**
```
source: https://perinim.github.io/projects
from bs4 import BeautifulSoup
import requests
url = "https://perinim.github.io/projects"
response = requests.get(url) …
```
=> bugfix: ScriptCreatorGraph verbose settings + RobotsNode handling model IDs

README.md, docs/chinese.md
The Chinese Readme is incomplete and contains some grammar errors. I have modified some sentences and supplemented the missing parts by referring to the English Readme.
Change the prompt in the code to English, as the Mistral in the example does not support Chinese.
=> Improve the Chinese Readme to synchronize with the English Readme.

README.md, docs/japanese.md
I created Japanese translated README.
=> docs: add Japanese README

scrapegraphai/builders/graph_builder.py, scrapegraphai/graphs/abstract_graph.py, scrapegraphai/models/ernie.py, tests/graphs/smart_scraper_ernie_test.py
=> support ernie

scrapegraphai/nodes/robots_node.py
- Changed the access of model_name from dictionary-style to attribute-style in llm_model to comply with langchain BaseChatModel.
- The code before will result in the error: `TypeError: 'OpenAI' object is not subscriptable` on line 114 when running the example code at examples/openai/custom_graph_openai.py
=> Refactor model_name attribute access in llm_model in robots_node.py

tests/graphs/scrape_json_ollama.py
This commit enhances the test suite for the JSON scraping pipeline by introducing the following improvements:
- Separate configuration from the test code by loading it from a JSON file (config.json)
- Use a parametrized fixture to run the test with multiple configurations automatically
- Read the sample JSON file from a separate inputs directory for better organization
- Add explicit assertions to verify the expected output (list of titles)
- Improve test organization and separation of concerns using fixtures
- Promote better coding practices and make the test suite more extensible
These changes aim to improve the testability, maintainability, and flexibility of the test suite. They make it easier to manage configurations, add or modify test cases, and ensure the robustness of the …
=> test: Enhance JSON scraping pipeline test

tests/nodes/fetch_node_test.py
This commit enhances the test suite for the FetchNode class by introducing mocking for the execute method using the unittest.mock module.
Changes:
- Imported the patch and MagicMock classes from unittest.mock.
- Decorated each test function with @patch('scrapegraphai.nodes.FetchNode.execute') to mock the execute method.
- Set the return_value of the mocked execute method to a MagicMock instance.
- Added assertions to check if the mocked execute method was called with the expected state dictionary.
- Updated the test functions to use the mocked execute method instead of the actual implementation.
Benefits:
- Improved test reliability by isolating the FetchNode class from external dependencies.
- Faster test execution since external resources (e.g., URLs, files) are not required.
- Better …
=> Enhance tests for FetchNode with mocking

tests/graphs/script_generator_test.py
This commit enhances the test suite for the ScriptCreatorGraph class by improving code readability, adding more informative assertions, and printing the prettified execution information.
Changes:
- Added more descriptive docstrings for better code documentation.
- Improved assertion messages to provide better debugging experience in case of failures.
- Added a line to print the prettified execution information using the `prettify_exec_info` function.
- Included a comment to remind developers to add additional assertions on the result or execution info if needed.
- Fixed a minor typo in the configuration dictionary (`beautifulsoup` instead of `beautifoulsoup`).
Benefits:
- Improved code readability and maintainability with better documentation.
- Enhanced debugging experience with more …
=> Test ScriptCreatorGraph and print execution info

tests/nodes/robot_node_test.py
- Added pytest fixture to set up the RobotsNode with the initial state.
- Implemented test_robots_node to test the execution of RobotsNode.
- Used unittest.mock.patch to mock the execute method, ensuring faster and more reliable tests without actual network calls.
- Added assertions to verify the correctness of the result and ensure the execute method is called once with the correct arguments.
=> feat: Add tests for RobotsNode and update test setup

scrapegraphai/docloaders/chromium.py, scrapegraphai/nodes/search_link_node.py
Some sites that rely on SPA type of architecture are returning HTML content before the page is properly populated with client side fetched data. 
When working with playwright, depending on the architecture of the scraped site, we may want to wait for different page events before considering a page "loaded" and ready to parse. 
This adds the ability to specify `load_state`, which defaults to `domcontentloaded` but can be overridden with other playwright load states: https://playwright.dev/python/docs/api/class-page#page-wait-for-load-state
=> Add the ability to specify load state

scrapegraphai/utils/proxy_rotation.py
As stated in the proxy documentation part [here](https://scrapegraph-ai.readthedocs.io/en/latest/scrapers/graph_config.html#proxy-rotation), this example shows proxy server address set to `http://your_proxy_server:port`, which throws an error since the IPv4 check is made with the URL scheme included such as `http://your_proxy_server`, thus causing the condition to skip and resulting in an `AssertionError`.
This pull request strips out any URL scheme found in the proxy server address, matching with the example provided within the documentation.
=> Strip out the scheme from the proxy server address URI.

scrapegraphai/graphs/base_graph.py
This PR fixes a small typo in the warning message.
Thank you for this great library.
=> Fix a small typo in the warning message

scrapegraphai/nodes/search_internet_node.py
Fix for issue https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/433
I did consider other options but found this to be the most clean option. 
(E.g. you could modify the base Ollama class and add a calling function to not use JSON or something)
=> Ollama: Use no json format when creating the search query

requirements-dev.lock, requirements.lock, requirements.txt, scrapegraphai/graphs/abstract_graph.py
=> fix(AbstractGraph): instantiation of Azure GPT models

scrapegraphai/graphs/abstract_graph.py
Included the code for Azure OpenAI to map the with models_tokens dictionary for getting model tokens.
=> Fix: Azure OpenAI issue

scrapegraphai/builders/graph_builder.py
Tried to run graph_builder from the Google Colab examples but failed to import GraphBuilder.
Issues:
1. scrapegraphai/models/__init__.py no longer has a model named Gemini.
2. Ernie was referenced but never imported.
Solutions:
1. Continuing the work by Marco Vinciguerra on [this commit](https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/203ee2c1862a12a399dac1f278a0d90ffdcd9e80), changed the imports to langchain models.
2. Minor fix of imports ordering to match rest of code (local repo imports last with space either side)
Checks:
1. Checked that both langchain_community and langchain_google_genai were already used and available.
2. Checked code could run without error
3. Linting and formatting matched
Further suggestions for future edits:
1. move imports down to within the if/else …
=> Graph Builder failed import bugfix

scrapegraphai/graphs/csv_scraper_multi_graph.py, scrapegraphai/graphs/json_scraper_multi_graph.py, scrapegraphai/graphs/markdown_scraper_multi_graph.py, scrapegraphai/graphs/omni_search_graph.py, scrapegraphai/graphs/pdf_scraper_multi_graph.py, scrapegraphai/graphs/script_creator_multi_graph.py, scrapegraphai/graphs/search_graph.py, scrapegraphai/graphs/smart_scraper_multi_graph.py, scrapegraphai/graphs/xml_scraper_multi_graph.py, scrapegraphai/utils/copy.py, tests/utils/copy_utils_test.py
link #609 
When copying the configuration with model_instance, an error may arise because model_instance is typically an uncopyable object. To fix it, I attempted to use safe_deepcopy to replace the internal deepcopy during the copying of the LLM configuration.
The safe_deepcopy function first attempts to use the internal deepcopy, ensuring it doesn't disrupt the original usage. If that fails, it resorts to alternative copying logic, such as shallow copying. In the worst-case scenario, it returns the original object.
If there are any new graphs using deepcopy in future pull requests, special attention should be paid to copying the LLM configuration correctly.
This pull request may not represent the best practice for resolving the issue, but it offers a quick fix. Here are some alternative …
=> fix: deepcopy fail for coping model_instance config

scrapegraphai/nodes/generate_answer_csv_node.py, scrapegraphai/nodes/generate_answer_node.py, scrapegraphai/nodes/generate_answer_omni_node.py, scrapegraphai/nodes/generate_answer_pdf_node.py, scrapegraphai/nodes/merge_answers_node.py
The fix works with:
- pydantic
- langchain_core.pydantic_v1
- TypedDict
=> Fixed pydantic errors when using `with_strctured_output`

scrapegraphai/docloaders/browser_base.py
- Updated `browser_base_fetch` function to accept either a single URL or a list of URLs
- Added `text_content` parameter to allow choosing between text-only and HTML output
- Improved type hinting for better code readability and IDE support
- Updated function documentation to reflect new capabilities
These changes enhance the flexibility and usability of the `browser_base_fetch` function, aligning it more closely with the latest Browserbase SDK interface. This update allows users to more easily fetch content from single or multiple URLs and choose between text-only and HTML output.
- Tested with single URL input
- Tested with multiple URL input
- Verified text-only and HTML output options
This update maintains backwards compatibility while extending functionality. Users of the existing …
=> feat(docloaders): Enhance browser_base_fetch function flexibility

scrapegraphai/graphs/csv_scraper_multi_graph.py, scrapegraphai/graphs/json_scraper_multi_graph.py, scrapegraphai/graphs/markdown_scraper_multi_graph.py, scrapegraphai/graphs/omni_search_graph.py, scrapegraphai/graphs/pdf_scraper_multi_graph.py, scrapegraphai/graphs/search_graph.py, scrapegraphai/graphs/smart_scraper_multi_graph.py, scrapegraphai/graphs/xml_scraper_multi_graph.py, scrapegraphai/nodes/generate_answer_csv_node.py, scrapegraphai/nodes/generate_answer_node.py, scrapegraphai/nodes/generate_answer_omni_node.py, scrapegraphai/nodes/generate_answer_pdf_node.py, scrapegraphai/nodes/graph_iterator_node.py, scrapegraphai/nodes/merge_answers_node.py, scrapegraphai/utils/llm_output_parser.py
Pydantic validation error happens when using IterativeGraph module.
Problem arises when the IterativeGraph module tries to use the same instantiation of a class for multiple execution, causing the class to not pass correctly llm into his functions.
- Modified Search graphs to move instantiation inside IterativeGraph
- IterativeGraph now creates multiple instances of the class we want to iterate over. This can be made better.
=> 598 - Fix pydantic validation error 

scrapegraphai/graphs/base_graph.py, scrapegraphai/utils/__init__.py, scrapegraphai/utils/custom_openai_callback.py
See #576 for a detailed explanation.
=> Added CustomOpenaiCallback to ensure exclusive access to nested data.

scrapegraphai/utils/copy.py, tests/utils/copy_utils_test.py
link https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/669
I got it. I follow the [boto3 document](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/copy.html) and find this is diffcult to copy without getting resource. So I try to return same obj. 
The resaon is the copy config will pass in the sub graph and the use same client.This means that copying and returning the original object have the same effect.
BTW, I refactor it shallow copy code and pass all test
=> fix:fix boto3 client copy

pyproject.toml
mistral-common dependency is necessary for tokeniser utilities while using MistralAI.
https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/pre/beta/scrapegraphai/utils/tokenizers/tokenizer_mistral.py
=> fix: Add mistral-common dependency

examples/groq/smart_scraper_groq.py, scrapegraphai/docloaders/chromium.py
undetected_chromedriver uses selenium backend and it can pass cloudflare on many websites. Also afaik, it is async by default.
=> feat: support for undetected_chromedriver with selenium backend

examples/extras/cond_smartscraper_usage.py, pyproject.toml, requirements.txt, scrapegraphai/graphs/base_graph.py, scrapegraphai/graphs/smart_scraper_graph.py, scrapegraphai/nodes/conditional_node.py, scrapegraphai/prompts/__init__.py, scrapegraphai/prompts/generate_answer_node_prompts.py
implemented a structured way to parse the graph config and map to the conditions. Currently, this is only to check `None` returned answers, Future implementation might involve the check for the schema match against the returned result.
```
graph_config = {
"llm": {
"api_key": os.getenv("GROQ_APIKEY"),
"model": "groq/gemma-7b-it",
},
"verbose": True,
"headless": True,
"reattempt": True
}
```
=> feat: add conditional node to the smart_scraper_graph

scrapegraphai/utils/tokenizer.py, scrapegraphai/utils/tokenizers/tokenizer_ollama.py, tests/graphs/smart_scraper_ollama_test.py
Fixes #752
Fix the issue with loading the tokenizer for 'gpt2'.
* **scrapegraphai/utils/tokenizer.py**
- Add a check for `GPT2TokenizerFast` in the `num_tokens_calculus` function.
- Import `GPT2TokenizerFast` from `transformers`.
* **scrapegraphai/utils/tokenizers/tokenizer_ollama.py**
- Modify the `num_tokens_ollama` function to handle `GPT2TokenizerFast`.
* **tests/graphs/smart_scraper_ollama_test.py**
- Add a test case to verify the tokenizer loading for `GPT2TokenizerFast`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/ScrapeGraphAI/Scrapegraph-ai/issues/752?shareId=90086761-059f-4618-9dc3-93d1f2586618).
=> Fix tokenizer loading for GPT2

examples/together/depth_search_graph_together.py, requirements-dev.lock, requirements.lock
This is not the bug we were looking for, there seems to be no bug at all. The code works just fine with the debugger. Yet, I found this little thing in the examples.
=> chore: fix example

scrapegraphai/graphs/abstract_graph.py
=> fix(AbstractGraph): manually select model tokens

Dockerfile
Remove unnecessary cache files and temporary data:
- Remove apt lists after package installation
- Use pip --no-cache-dir flag
Image size comparison:
```
REPOSITORY         TAG      IMAGE ID       CREATED          SIZE
scrapegraph-ai     after    609a2ecf4678   20 minutes ago   3.1GB
scrapegraph-ai     before   e3093b782ab0   24 minutes ago   3.39GB
```
This reduced about 0.29GB image size by preventing cache files from being included in the final image layers.
=> Clean up cache files to reduce Docker image size

scrapegraphai/nodes/parse_node.py
The method `_extract_urls` of the `parse_node` was not extracting well formed URLs, causing problems when using the function `urljoin` from `urllib.parse` (ref. issue #822). These changes try to parse the URLs more precisely including: "absolute" URLs (e.g.: "www.website.com/...", "http://www.website.com/...", "https://www.website.com/...", "website.com/...", "http://website.com/...", "https://website.com/...", etc.), image URLs, "relative" URLs (e.g.: "/test/page.html", "/?test=test", etc.) which will be joined later with the source URL.
=> fix: improved links (URLs) extraction for parse_node, resolves #822

scrapegraphai/nodes/fetch_node.py
If you pass a string with the downloaded html as input, the scraper will fail because it will check if the input is a valid url.
The solution below checks whether the input type is a url _before_ trying to validate the url itself. This now works both for url and html input types.
The issue was first reported in #735 but it's falsely closed.
=> fix: validate URL only if the input type is a URL

examples/extras/chromium_selenium.py, scrapegraphai/docloaders/chromium.py
Issue - #772 
Added functionality to switch browsers by modifying the code and included the Firefox support for Selenium and Playwright.
=> #772 added functionality to change browser to firefox

requirements-dev.txt, scrapegraphai/graphs/abstract_graph.py, tests/graphs/abstract_graph_test.py
Issue https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/711
Issue https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/179
This PR introduces an optional `run_safe_async` function to ensure compatibility and safety when running the scrape process in environments that use asyncio, such as FastAPI. The function allows seamless execution of the run method within an asynchronous context, mitigating potential issues with blocking operations or event loop conflicts.
=> #771 Fix/feat - Run safe async

scrapegraphai/graphs/smart_scraper_graph.py
Issue - #710 
In this issue, there are two ways to solve the problem. The first method is to introduce a verbose option in the SmartScraperGraph. This will allow for detailed logging functionality for those who want to see it. The second method is to write a custom function that triggers the page loading and extracts data only once the page has fully loaded. I can add the custom code example in the issue panel or wherever you prefer.
Making significant changes to the legacy code can be quite challenging to maintain. However, I have done my best to keep the code clean and concise.
=> #710 - just a check added for the detailed logging

examples/local_models/smart_scraper_ollama.py, examples/local_models/smart_scraper_schema_ollama.py, pyproject.toml, scrapegraphai/docloaders/chromium.py, scrapegraphai/graphs/abstract_graph.py, scrapegraphai/nodes/generate_answer_node.py, scrapegraphai/nodes/generate_answer_node_k_level.py, scrapegraphai/nodes/parse_node.py, scrapegraphai/utils/split_text_into_chunks.py, scrapegraphai/utils/tokenizer.py, scrapegraphai/utils/tokenizers/tokenizer_openai.py, uv.lock
- Fixed 1024 max tokens bug for Ollama models
- Added new structured output for Ollama models
- Exposed Browser backend to config loader_kwargs
=> 856 token indices sequence length

scrapegraphai/graphs/abstract_graph.py, scrapegraphai/graphs/code_generator_graph.py, scrapegraphai/graphs/csv_scraper_graph.py, scrapegraphai/graphs/csv_scraper_multi_graph.py, scrapegraphai/graphs/depth_search_graph.py, scrapegraphai/graphs/document_scraper_graph.py, scrapegraphai/graphs/document_scraper_multi_graph.py, scrapegraphai/graphs/json_scraper_graph.py, scrapegraphai/graphs/json_scraper_multi_graph.py, scrapegraphai/graphs/omni_scraper_graph.py, scrapegraphai/graphs/omni_search_graph.py, scrapegraphai/graphs/screenshot_scraper_graph.py, scrapegraphai/graphs/script_creator_graph.py, scrapegraphai/graphs/script_creator_multi_graph.py, scrapegraphai/graphs/search_graph.py, scrapegraphai/graphs/search_link_graph.py, scrapegraphai/graphs/smart_scraper_graph.py, scrapegraphai/graphs/smart_scraper_lite_graph.py, scrapegraphai/graphs/smart_scraper_multi_concat_graph.py, scrapegraphai/graphs/smart_scraper_multi_graph.py, scrapegraphai/graphs/smart_scraper_multi_lite_graph.py, scrapegraphai/graphs/speech_graph.py, scrapegraphai/graphs/xml_scraper_graph.py, scrapegraphai/graphs/xml_scraper_multi_graph.py, scrapegraphai/nodes/graph_iterator_node.py
Related to this issue https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/894.
I changed all the types related to the parameter schema and imported the Type from typing.
=> fix: Schema parameter type

scrapegraphai/nodes/generate_answer_node.py
Fixes https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/926
Bug introduced with commit https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/5c0bc46c6322ea07efa31d95819d7da47462f981
=> bugfix: KeyError mishap

scrapegraphai/utils/code_error_analysis.py, scrapegraphai/utils/code_error_correction.py, scrapegraphai/utils/research_web.py
- Add Pydantic models for state validation in code_error_analysis.py and code_error_correction.py
- Implement comprehensive key existence checks to prevent KeyError exceptions
- Create custom exception hierarchy for better error management
- Add improved PDF detection with regex pattern matching in research_web.py
- Implement input validation for all public functions
- Add detailed error messages and type hints
=> feat: enhance error handling and validation across utility modules

README.md
This is a really minor spelling error. "cna" -> "can".
I did not fork from the pre/beta branch as main README seemed to be ahead (version = "1.51.0" vs "1.50.0b1")
=> fix: 🐛 Spelling fix for README.md

CHANGELOG.md, pyproject.toml
* add new openai models ([97ee48c](https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/97ee48cb52038ec746d8ec78de029c8dde6a7753))
* **release:** 1.49.0-beta.1 [skip ci] ([228920c](https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/228920cf10e0861ada99432f34fca2f5b845984f))
=> ci(release): 1.50.0-beta.1 [skip ci]
